apiVersion: apps/v1
kind: Deployment
metadata:
  name: exam-scheduler
spec:
  replicas: 3
  selector:
    matchLabels:
      app: exam-scheduler
  template:
    metadata:
      labels:
        app: exam-scheduler
    spec:
      containers:
      - name: backend
        image: exam-scheduler-backend:1.0.0
